/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface TestContractAbiInterface extends Interface {
  functions: {
    decrement_counter: FunctionFragment;
    get_count: FunctionFragment;
    increment_counter: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'decrement_counter', values: [BigNumberish]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_count', values: []): Uint8Array;
  encodeFunctionData(functionFragment: 'increment_counter', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'decrement_counter', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_count', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'increment_counter', data: BytesLike): DecodedValue;
}

export class TestContractAbi extends Contract {
  interface: TestContractAbiInterface;
  functions: {
    decrement_counter: InvokeFunction<[amount: BigNumberish], BN>;
    get_count: InvokeFunction<[], BN>;
    increment_counter: InvokeFunction<[amount: BigNumberish], BN>;
  };
}
